version: '3.8'

services:
  quiz-app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    container_name: quizmind-quiz-app
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    networks:
      - quizmind-network

networks:
  quizmind-network:
    name: quizmind_default 